// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDet4RQYvv8520zth2hxlzsGXaaEjHCGU',
    appId: '1:426072357487:web:9d211aaf06b6a02137eb9a',
    messagingSenderId: '426072357487',
    projectId: 'webrtc-1b940',
    authDomain: 'webrtc-1b940.firebaseapp.com',
    storageBucket: 'webrtc-1b940.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2jUHN17RDe04lVITHgvANUjhU8HQB_EI',
    appId: '1:426072357487:android:1e5bf1aaa0a2a6c937eb9a',
    messagingSenderId: '426072357487',
    projectId: 'webrtc-1b940',
    storageBucket: 'webrtc-1b940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkb_XSmUDeYRlN4FYwK8KGYkXGn5Tgd68',
    appId: '1:426072357487:ios:5cb890e4b7086d3837eb9a',
    messagingSenderId: '426072357487',
    projectId: 'webrtc-1b940',
    storageBucket: 'webrtc-1b940.firebasestorage.app',
    iosBundleId: 'com.example.servidorWebrtc',
  );
}
